default: &default
  project_id: [PROJECT_ID]
  default_topic: [TOPIC]
  default_subscription: [SUB]
  pubsub_credentials_path: [CREDENTIALS_PATH]

development:
  <<: *default

production:
  <<: *default
